### ISSUE TITLE
Arachnid requires that spider be in /home/ezra

### ISSUE THREAD

**Issue by jamesmkrieger** [ezralanglois/arachnid#8]
Otherwise it said it could not find the spider binary even though it was specified on the GUI.

**Comment by ezralanglois** [comment]
Thanks will look into this when I get a chance.

**Comment by ezralanglois** [comment]
If you can provide an exception stack trace or crash report, that would be a big help. I don't remember the code well enough to fix this quickly at the moment.

**Comment by jamesmkrieger** [comment]
I'm failing to reproduce this bug now. The controller won't go back to the previous steps.

**Comment by jamesmkrieger** [comment]
It is now running spider as /data/jkrieger/programs/anaconda2/bin/spider_linux_mp_opt64 but there is something else not found in the traceback.

/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/tracing.py:448: UserWarning: Duplicate name: '.ara-control.crash_report_2017_07_27_15_24_43.0'
  try: zf.write(filename, arcname=arcname)#, compress_type=zipfile.ZIP_STORED)
/data/jkrieger/programs/anaconda2/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
/data/jkrieger/programs/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/tracing.py:448: UserWarning: Duplicate name: 'project_2017_07_27_15_24_43.log'
  try: zf.write(filename, arcname=arcname)#, compress_type=zipfile.ZIP_STORED)
/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/tracing.py:448: UserWarning: Duplicate name: 'project_2017_07_27_15_25_55.log'
  try: zf.write(filename, arcname=arcname)#, compress_type=zipfile.ZIP_STORED)
/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/tracing.py:448: UserWarning: Duplicate name: '.ara-control.crash_report_2017_07_27_15_25_55.0'
  try: zf.write(filename, arcname=arcname)#, compress_type=zipfile.ZIP_STORED)
  
  \__`O O'__/        SPIDER -- COPYRIGHT
  ,__xXXXx___        HEALTH RESEARCH INC., ALBANY, NY.
   __xXXXx__
  /  /xxx\  \        VERSION:  UNIX  21.00 ISSUED: 01/03/2013
    /     \          DATE:     27-JUL-2017    AT  15:25:55

  If SPIDER is useful, please cite:
  Frank J, Radermacher M, Penczek P, Zhu J, Li Y, Ladjadj M,  Leith A.
  SPIDER and WEB: Processing and visualization of images in 3D electron 
  microscopy and related fields.  J. Struct. Biol. 1996; 116: 190-199.
  
 .ENTER PROJECT/DATA EXTENSION:      dat


*** FILE NOT FOUND: /guam.raid.cluster.software/spider.18.15/bin/Nextresults                       

 Results file: results.dat.000                                                                 
 Running: /data/jkrieger/programs/anaconda2/bin/spider_linux_mp_opt64                                                                                                     
 .OPERATION:  MD
 .MODE:      RESULTS OFF
  RESULTS FILE TERMINATED AT USERS REQUEST
  
 .OPERATION:  MD
 .MODE:      TERM OFF

**Comment by jamesmkrieger** [comment]
The files related to this are copied here. I'm not sure if this is the same issue or not though.

> jkrieger@zeus:/data/jkrieger/programs/arachnid_skype_day$ cat .ara-control.crash_report.0 
2017-07-27 15:25:56,079 WARNING Failed to load EMAN2 module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_filter.so module
2017-07-27 15:25:56,079 WARNING Failed to load _image_utility.so module - certain functions will not be available
2017-07-27 15:25:56,079 WARNING Failed to load _resample.so module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_interpolate.so module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_rotate.so module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_rotate.so module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_ctf.so module
2017-07-27 15:25:56,079 WARNING Failed to load _spider_reconstruct.so
2017-07-27 15:25:56,080 INFO Program: arachnid.app.autopick
2017-07-27 15:25:56,080 INFO Version: UNKNOWN
2017-07-27 15:25:56,080 INFO PID: 5878
2017-07-27 15:25:56,080 INFO Created: 1501183554
2017-07-27 15:25:56,080 INFO Multi-threading with OpenMP - enabled
2017-07-27 15:25:56,082 INFO Multi-threading with OpenMP - set thread count to 1
2017-07-27 15:25:56,082 INFO Skipping 0 files - restarting from the beginning - configuration file changed
2017-07-27 15:25:56,082 INFO Mask Multiplier: 1.000000
2017-07-27 15:25:56,082 INFO Peak limit: 2000.000000
2017-07-27 15:25:56,082 ERROR ***Unexpected error occurred: AttributeError: 'NoneType' object has no attribute 'sinc_blackman_kernel'


See .ara-control.crash_report for more details
2017-07-27 15:25:56,082 ERROR Unexpected error occurred
Traceback (most recent call last):
  File "/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/program.py", line 314, in launch_program
    main_template.main(args, main_module, **param)
  File "/data/jkrieger/programs/arachnid_skype_day/arachnid/core/app/file_processor.py", line 206, in main
    f = initialize(files, extra)
  File "/data/jkrieger/programs/arachnid_skype_day/arachnid/app/autopick.py", line 775, in initialize
    return sorted(lfcpick.initialize(files, param))
  File "/data/jkrieger/programs/arachnid_skype_day/arachnid/app/lfcpick.py", line 354, in initialize
    param["ds_kernel"] = ndimage_interpolate.sincblackman(param['bin_factor'], dtype=numpy.float32)
  File "/data/jkrieger/programs/arachnid_skype_day/arachnid/core/image/ndimage_interpolate.py", line 163, in sincblackman
    _resample.sinc_blackman_kernel(kernel, int(template_min), float(frequency_cutoff))
AttributeError: 'NoneType' object has no attribute 'sinc_blackman_kernel'
2017-07-27 15:25:56,083 INFO Workflow ended
jkrieger@zeus:/data/jkrieger/programs/arachnid_skype_day$ cat project.log 
2017-07-27 15:25:56,080 INFO Program: arachnid.app.autopick
2017-07-27 15:25:56,080 INFO PID: 5878
2017-07-27 15:25:56,080 INFO Created: 1501183554
2017-07-27 15:25:56,080 INFO Multi-threading with OpenMP - enabled
2017-07-27 15:25:56,082 INFO Multi-threading with OpenMP - set thread count to 1
2017-07-27 15:25:56,082 INFO Skipping 0 files - restarting from the beginning - configuration file changed
2017-07-27 15:25:56,082 INFO Mask Multiplier: 1.000000
2017-07-27 15:25:56,082 INFO Peak limit: 2000.000000
2017-07-27 15:25:56,082 ERROR ***Unexpected error occurred: AttributeError: 'NoneType' object has no attribute 'sinc_blackman_kernel'


See .ara-control.crash_report for more details
2017-07-27 15:25:56,083 INFO Workflow ended
jkrieger@zeus:/data/jkrieger/programs/arachnid_skype_day$ cat control.log 
2017-07-27 15:25:53,301 WARNING Assuming image is MRC format - format is not correct (Likely this image came from Yifan's GPU alignment)

**Comment by ezralanglois** [comment]
Try the following, it may fix the problem

python setup.py build_ext --inplace

**Comment by jamesmkrieger** [comment]
That doesn't make any binaries in my path. Where did it put them?

**Comment by ezralanglois** [comment]
It should place the binaries in the same folder as the source files.
This allows Python to find them easier.

If that does not work, then you may just need to run the install command.
If you do that then you have to remember to run it after each change.

**Comment by jamesmkrieger** [comment]
No, that didn't work:

jkrieger@zeus:~/programs/arachnid_copy$ sudo find / -iname ara-control
/data/jkrieger/programs/anaconda2/pkgs/arachnid-dev-0.2.0-py27_1/bin/ara-control
/data/jkrieger/bin/EMAN2.2/bin/ara-control

**Comment by ezralanglois** [comment]
Sorry, I should have said shared libs, the .so files
